FLASK_APP=run.py
FLASK_ENV= # flask environment
FIREBASE_BUCKET= # firebase bucket link
FIREBASE_KEY=firebaseKey.json
ELASTICSEARCH_URL= # elasticsearch url
SECRET_KEY= # some strong password
MAIL_ADMIN= # application admin email
MAIL_USERNAME= # application email
MAIL_PASSWORD= # application email password